version: 2
jobs:
  build-publish-latest:
    environment:
      IMAGE_NAME: shashankkoppar/crispy-succotash
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  deploy-crispy-latest:
    environment:
      CLUSTER_NAME: koppar-crispy
      APP_NAME: crispy-succotash
      CLUSTER_REGION: europe-west1
      GKE_PROJECT: crispy-317519
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy Docker Image to Kubernetes Cluster
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT_KEY > $PWD/gcloud.json
            gcloud auth activate-service-account --key-file=$PWD/gcloud.json
            gcloud container clusters get-credentials ${CLUSTER_NAME} --region ${CLUSTER_REGION} --project ${GKE_PROJECT}
            apt-get update -y && apt-get install wget -y
            wget -O- https://k14s.io/install.sh | bash
            kubectl create configmap gcloud-config -n default --from-file=$PWD/gcloud.json --dry-run -o yaml > deploy/config.yaml
            kapp deploy --namespace default -a ${APP_NAME} -f deploy/ -y
            kapp inspect --namespace default -a ${APP_NAME}
            kapp logs --namespace default -a ${APP_NAME}

workflows:
  version: 2
  build-master:
    jobs:
      - build-publish-latest:
          filters:
            branches:
              only: master
      - deploy-crispy-latest:
          requires:
            - build-publish-latest
          filters:
            branches:
              only:
                - master
