version: 2
jobs:
  build-publish-latest:
    environment:
      IMAGE_NAME: shashankkoppar/crispy-succotash
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
  deploy-crispy-latest:
    environment:
      CLUSTER_NAME: crispy-succotash
      CLUSTER_REGION: europe-west1
      GKE_PROJECT: crispy-317519
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT_KEY > $PWD/gcloud.json
            gcloud auth activate-service-account --key-file=$PWD/gcloud.json
            gcloud components install kubectl
            gcloud container clusters get-credentials ${CLUSTER_NAME} --region ${CLUSTER_REGION} --project ${GKE_PROJECT}
            kubectl get nodes

workflows:
  version: 2
  build-master:
    jobs:
      - build-publish-latest:
          filters:
            branches:
              only: master
      - build-push-image-and-dag:
          requires:
            - build-publish-latest
          filters:
            branches:
              only:
                - master
