version: 2
jobs:
  build-publish-latest:
    environment:
      IMAGE_NAME: shashankkoppar/crispy-succotash
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker Image to Docker Hub
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build-publish-latest:
          filters:
            branches:
              only: master
