apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - command:
          - /cloud_sql_proxy
          - -instances=crispy-317519:europe-west1:postgres-instance=tcp:5432
          - -credential_file=/secrets/cloudsql/gcloud.json
          image: gcr.io/cloudsql-docker/gce-proxy
          imagePullPolicy: Always
          name: cloudsql-proxy
          resources:
            requests:
              cpu: 100m
          volumeMounts:
          - mountPath: /secrets/cloudsql
            name: gcloud-config
        - env:
            - name: APP_TYPE
              value: app
            - name: DB_HOST
              value: localhost
            - name: DJANGO_SETTINGS_MODULE
              value: crispy.settings.docker
          image: shashankkoppar/crispy-succotash
          name: app
          ports:
            - containerPort: 8000
      volumes:
        - name: gcloud-config
          configMap:
            name: gcloud-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: app
