apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - command:
          - /cloud_sql_proxy
          - -instances=crispy-317519:europe-west1:postgres-instance=tcp:5432
          - -credential_file=/secrets/cloudsql/gcloud.json
          image: gcr.io/cloudsql-docker/gce-proxy
          imagePullPolicy: Always
          name: cloudsql-proxy
          resources:
            requests:
              cpu: 100m
          volumeMounts:
          - mountPath: /secrets/cloudsql
            name: gcloud-config
        - env:
            - name: APP_TYPE
              value: worker
            - name: DB_HOST
              value: localhost
            - name: LOADBALANCER_IP
              value: '35.205.189.209' #Update with loadbalancer ip recieved after deploying service first time and rerun              
          image: shashankkoppar/crispy-succotash
          name: worker
      restartPolicy: Always
      volumes:
        - name: gcloud-config
          configMap:
            name: gcloud-config
